function C = CellComp4Layer_Coefficients_Full(Coeff,eta_V,eta_F,eta_L,eta_I,sigma_V,xi_T_f,sigma_L_y,sigma_I,Yii, h_F, m)

if strcmpi(Coeff,'A1')
    
    C = (2.*eta_V.*m.*exp(Yii.*eta_I).*(exp(Yii.*eta_V)./2 + ...
        exp(-Yii.*eta_V)./2).*(eta_L.*sigma_L_y.*exp(Yii.*eta_V + 2.*eta_F.*h_F) + ...
        eta_F.*xi_T_f.*exp(Yii.*eta_V + 2.*eta_F.*h_F) - ...
        eta_L.*sigma_L_y.*exp(Yii.*eta_V) + ...
        eta_F.*xi_T_f.*exp(Yii.*eta_V)).*sigma_V.^2 - ...
        eta_F.*m.*xi_T_f.*exp(Yii.*eta_I).*(eta_L.*sigma_L_y - eta_F.*xi_T_f - ...
        eta_L.*sigma_L_y.*exp(2.*Yii.*eta_V + 2.*eta_F.*h_F) - ...
        eta_F.*xi_T_f.*exp(2.*Yii.*eta_V + 2.*eta_F.*h_F) - ...
        eta_L.*sigma_L_y.*exp(2.*Yii.*eta_V) + eta_F.*xi_T_f.*exp(2.*Yii.*eta_V) + ...
        eta_L.*sigma_L_y.*exp(2.*eta_F.*h_F) + ...
        eta_F.*xi_T_f.*exp(2.*eta_F.*h_F)).*sigma_V)./(exp(2.*eta_F.*h_F).*(eta_I.*sigma_I ...
        - eta_V.*sigma_V).*(eta_V.*sigma_V - eta_F.*xi_T_f).*(eta_L.*sigma_L_y + ...
        eta_F.*xi_T_f) + exp(2.*Yii.*eta_V + 2.*eta_F.*h_F).*(eta_I.*sigma_I + ...
        eta_V.*sigma_V).*(eta_V.*sigma_V + eta_F.*xi_T_f).*(eta_L.*sigma_L_y + ...
        eta_F.*xi_T_f) - ...
        2.*eta_L.*eta_V.^2.*sigma_V.^2.*sigma_L_y.*(exp(2.*Yii.*eta_V)./2 - 1./2) - ...
        2.*eta_F.^2.*eta_I.*sigma_I.*xi_T_f.^2.*(exp(2.*Yii.*eta_V)./2 - 1./2) + ...
        2.*eta_F.*eta_V.^2.*sigma_V.^2.*xi_T_f.*(exp(2.*Yii.*eta_V)./2 - 1./2) - ...
        2.*eta_F.^2.*eta_V.*sigma_V.*xi_T_f.^2.*(exp(2.*Yii.*eta_V)./2 + 1./2) - ...
        eta_I.*eta_L.*eta_V.*sigma_I.*sigma_V.*sigma_L_y.*(exp(2.*Yii.*eta_V) + 1) + ...
        eta_F.*eta_I.*eta_V.*sigma_I.*sigma_V.*xi_T_f.*(exp(2.*Yii.*eta_V) + 1) + ...
        eta_F.*eta_I.*eta_L.*sigma_I.*sigma_L_y.*xi_T_f.*(exp(2.*Yii.*eta_V) - 1) + ...
        eta_F.*eta_L.*eta_V.*sigma_V.*sigma_L_y.*xi_T_f.*(exp(2.*Yii.*eta_V) + 1));
    
elseif strcmpi(Coeff,'B1')
    
    C = (eta_V.*m.*(eta_L.*sigma_L_y.*exp(Yii.*eta_V + 2.*eta_F.*h_F) + ...
        eta_F.*xi_T_f.*exp(Yii.*eta_V + 2.*eta_F.*h_F) - ...
        eta_L.*sigma_L_y.*exp(Yii.*eta_V) + ...
        eta_F.*xi_T_f.*exp(Yii.*eta_V)).*sigma_V.^2 - ...
        eta_F.*m.*xi_T_f.*(eta_L.*sigma_L_y.*exp(Yii.*eta_V + 2.*eta_F.*h_F) + ...
        eta_F.*xi_T_f.*exp(Yii.*eta_V + 2.*eta_F.*h_F) + ...
        eta_L.*sigma_L_y.*exp(Yii.*eta_V) - ...
        eta_F.*xi_T_f.*exp(Yii.*eta_V)).*sigma_V)./(exp(2.*eta_F.*h_F).*(eta_I.*sigma_I ...
        - eta_V.*sigma_V).*(eta_V.*sigma_V - eta_F.*xi_T_f).*(eta_L.*sigma_L_y + ...
        eta_F.*xi_T_f) + exp(2.*Yii.*eta_V + 2.*eta_F.*h_F).*(eta_I.*sigma_I + ...
        eta_V.*sigma_V).*(eta_V.*sigma_V + eta_F.*xi_T_f).*(eta_L.*sigma_L_y + ...
        eta_F.*xi_T_f) - ...
        2.*eta_L.*eta_V.^2.*sigma_V.^2.*sigma_L_y.*(exp(2.*Yii.*eta_V)./2 - 1./2) - ...
        2.*eta_F.^2.*eta_I.*sigma_I.*xi_T_f.^2.*(exp(2.*Yii.*eta_V)./2 - 1./2) + ...
        2.*eta_F.*eta_V.^2.*sigma_V.^2.*xi_T_f.*(exp(2.*Yii.*eta_V)./2 - 1./2) - ...
        2.*eta_F.^2.*eta_V.*sigma_V.*xi_T_f.^2.*(exp(2.*Yii.*eta_V)./2 + 1./2) - ...
        eta_I.*eta_L.*eta_V.*sigma_I.*sigma_V.*sigma_L_y.*(exp(2.*Yii.*eta_V) + 1) + ...
        eta_F.*eta_I.*eta_V.*sigma_I.*sigma_V.*xi_T_f.*(exp(2.*Yii.*eta_V) + 1) + ...
        eta_F.*eta_I.*eta_L.*sigma_I.*sigma_L_y.*xi_T_f.*(exp(2.*Yii.*eta_V) - 1) + ...
        eta_F.*eta_L.*eta_V.*sigma_V.*sigma_L_y.*xi_T_f.*(exp(2.*Yii.*eta_V) + 1));
    
elseif strcmp(Coeff,'B2')
    
    C = -(m.*exp(-Yii.*eta_V).*(eta_I.*sigma_I - ...
        eta_V.*sigma_V).*(eta_F.^2.*xi_T_f.^2.*(exp(2.*Yii.*eta_V + 2.*eta_F.*h_F) + 1) ...
        - exp(2.*Yii.*eta_V).*(eta_V.*sigma_V - eta_F.*xi_T_f).*(eta_L.*sigma_L_y - ...
        eta_F.*xi_T_f) + exp(2.*eta_F.*h_F).*(eta_V.*sigma_V - ...
        eta_F.*xi_T_f).*(eta_L.*sigma_L_y + eta_F.*xi_T_f) + ...
        eta_L.*eta_V.*sigma_V.*sigma_L_y.*(exp(2.*Yii.*eta_V + 2.*eta_F.*h_F) - 1) + ...
        eta_F.*eta_V.*sigma_V.*xi_T_f.*(exp(2.*Yii.*eta_V + 2.*eta_F.*h_F) + 1) + ...
        eta_F.*eta_L.*sigma_L_y.*xi_T_f.*(exp(2.*Yii.*eta_V + 2.*eta_F.*h_F) - ...
        1)))./(2.*eta_V.*(exp(2.*eta_F.*h_F).*(eta_I.*sigma_I - ...
        eta_V.*sigma_V).*(eta_V.*sigma_V - eta_F.*xi_T_f).*(eta_L.*sigma_L_y + ...
        eta_F.*xi_T_f) + exp(2.*Yii.*eta_V + 2.*eta_F.*h_F).*(eta_I.*sigma_I + ...
        eta_V.*sigma_V).*(eta_V.*sigma_V + eta_F.*xi_T_f).*(eta_L.*sigma_L_y + ...
        eta_F.*xi_T_f) - ...
        2.*eta_L.*eta_V.^2.*sigma_V.^2.*sigma_L_y.*(exp(2.*Yii.*eta_V)./2 - 1./2) - ...
        2.*eta_F.^2.*eta_I.*sigma_I.*xi_T_f.^2.*(exp(2.*Yii.*eta_V)./2 - 1./2) + ...
        2.*eta_F.*eta_V.^2.*sigma_V.^2.*xi_T_f.*(exp(2.*Yii.*eta_V)./2 - 1./2) - ...
        2.*eta_F.^2.*eta_V.*sigma_V.*xi_T_f.^2.*(exp(2.*Yii.*eta_V)./2 + 1./2) - ...
        eta_I.*eta_L.*eta_V.*sigma_I.*sigma_V.*sigma_L_y.*(exp(2.*Yii.*eta_V) + 1) + ...
        eta_F.*eta_I.*eta_V.*sigma_I.*sigma_V.*xi_T_f.*(exp(2.*Yii.*eta_V) + 1) + ...
        eta_F.*eta_I.*eta_L.*sigma_I.*sigma_L_y.*xi_T_f.*(exp(2.*Yii.*eta_V) - 1) + ...
        eta_F.*eta_L.*eta_V.*sigma_V.*sigma_L_y.*xi_T_f.*(exp(2.*Yii.*eta_V) + 1)));
    
elseif strcmpi(Coeff,'C1')
    
    C = -(2.*eta_V.*m.*sigma_V.^2.*exp(Yii.*eta_V).*(eta_L.*sigma_L_y - ...
        eta_F.*xi_T_f))./(exp(2.*eta_F.*h_F).*(eta_I.*sigma_I - ...
        eta_V.*sigma_V).*(eta_V.*sigma_V - eta_F.*xi_T_f).*(eta_L.*sigma_L_y + ...
        eta_F.*xi_T_f) + exp(2.*Yii.*eta_V + 2.*eta_F.*h_F).*(eta_I.*sigma_I + ...
        eta_V.*sigma_V).*(eta_V.*sigma_V + eta_F.*xi_T_f).*(eta_L.*sigma_L_y + ...
        eta_F.*xi_T_f) - ...
        2.*eta_L.*eta_V.^2.*sigma_V.^2.*sigma_L_y.*(exp(2.*Yii.*eta_V)./2 - 1./2) - ...
        2.*eta_F.^2.*eta_I.*sigma_I.*xi_T_f.^2.*(exp(2.*Yii.*eta_V)./2 - 1./2) + ...
        2.*eta_F.*eta_V.^2.*sigma_V.^2.*xi_T_f.*(exp(2.*Yii.*eta_V)./2 - 1./2) - ...
        2.*eta_F.^2.*eta_V.*sigma_V.*xi_T_f.^2.*(exp(2.*Yii.*eta_V)./2 + 1./2) - ...
        eta_I.*eta_L.*eta_V.*sigma_I.*sigma_V.*sigma_L_y.*(exp(2.*Yii.*eta_V) + 1) + ...
        eta_F.*eta_I.*eta_V.*sigma_I.*sigma_V.*xi_T_f.*(exp(2.*Yii.*eta_V) + 1) + ...
        eta_F.*eta_I.*eta_L.*sigma_I.*sigma_L_y.*xi_T_f.*(exp(2.*Yii.*eta_V) - 1) + ...
        eta_F.*eta_L.*eta_V.*sigma_V.*sigma_L_y.*xi_T_f.*(exp(2.*Yii.*eta_V) + 1));
    
elseif strcmpi(Coeff,'C2')
    
    C = (2.*eta_V.*m.*sigma_V.^2.*exp(Yii.*eta_V + ...
        2.*eta_F.*h_F).*(eta_L.*sigma_L_y + ...
        eta_F.*xi_T_f))./(exp(2.*eta_F.*h_F).*(eta_I.*sigma_I - ...
        eta_V.*sigma_V).*(eta_V.*sigma_V - eta_F.*xi_T_f).*(eta_L.*sigma_L_y + ...
        eta_F.*xi_T_f) + exp(2.*Yii.*eta_V + 2.*eta_F.*h_F).*(eta_I.*sigma_I + ...
        eta_V.*sigma_V).*(eta_V.*sigma_V + eta_F.*xi_T_f).*(eta_L.*sigma_L_y + ...
        eta_F.*xi_T_f) - ...
        2.*eta_L.*eta_V.^2.*sigma_V.^2.*sigma_L_y.*(exp(2.*Yii.*eta_V)./2 - 1./2) - ...
        2.*eta_F.^2.*eta_I.*sigma_I.*xi_T_f.^2.*(exp(2.*Yii.*eta_V)./2 - 1./2) + ...
        2.*eta_F.*eta_V.^2.*sigma_V.^2.*xi_T_f.*(exp(2.*Yii.*eta_V)./2 - 1./2) - ...
        2.*eta_F.^2.*eta_V.*sigma_V.*xi_T_f.^2.*(exp(2.*Yii.*eta_V)./2 + 1./2) - ...
        eta_I.*eta_L.*eta_V.*sigma_I.*sigma_V.*sigma_L_y.*(exp(2.*Yii.*eta_V) + 1) + ...
        eta_F.*eta_I.*eta_V.*sigma_I.*sigma_V.*xi_T_f.*(exp(2.*Yii.*eta_V) + 1) + ...
        eta_F.*eta_I.*eta_L.*sigma_I.*sigma_L_y.*xi_T_f.*(exp(2.*Yii.*eta_V) - 1) + ...
        eta_F.*eta_L.*eta_V.*sigma_V.*sigma_L_y.*xi_T_f.*(exp(2.*Yii.*eta_V) + 1));
    
elseif strcmpi(Coeff,'D2')
    
    C = (4.*eta_F.*eta_V.*m.*sigma_V.^2.*xi_T_f.*exp(Yii.*eta_V).*exp(eta_F.*h_F).* ...
        exp(eta_L.*h_F))./(exp(2.*eta_F.*h_F).*(eta_I.*sigma_I ...
        - eta_V.*sigma_V).*(eta_V.*sigma_V - eta_F.*xi_T_f).*(eta_L.*sigma_L_y + ...
        eta_F.*xi_T_f) + exp(2.*Yii.*eta_V + 2.*eta_F.*h_F).*(eta_I.*sigma_I + ...
        eta_V.*sigma_V).*(eta_V.*sigma_V + eta_F.*xi_T_f).*(eta_L.*sigma_L_y + ...
        eta_F.*xi_T_f) - ...
        2.*eta_L.*eta_V.^2.*sigma_V.^2.*sigma_L_y.*(exp(2.*Yii.*eta_V)./2 - 1./2) - ...
        2.*eta_F.^2.*eta_I.*sigma_I.*xi_T_f.^2.*(exp(2.*Yii.*eta_V)./2 - 1./2) + ...
        2.*eta_F.*eta_V.^2.*sigma_V.^2.*xi_T_f.*(exp(2.*Yii.*eta_V)./2 - 1./2) - ...
        2.*eta_F.^2.*eta_V.*sigma_V.*xi_T_f.^2.*(exp(2.*Yii.*eta_V)./2 + 1./2) - ...
        eta_I.*eta_L.*eta_V.*sigma_I.*sigma_V.*sigma_L_y.*(exp(2.*Yii.*eta_V) + 1) + ...
        eta_F.*eta_I.*eta_V.*sigma_I.*sigma_V.*xi_T_f.*(exp(2.*Yii.*eta_V) + 1) + ...
        eta_F.*eta_I.*eta_L.*sigma_I.*sigma_L_y.*xi_T_f.*(exp(2.*Yii.*eta_V) - 1) + ...
        eta_F.*eta_L.*eta_V.*sigma_V.*sigma_L_y.*xi_T_f.*(exp(2.*Yii.*eta_V) + 1));
    
end